### ISSUE TITLE
Compatibility with Goldmark (the new default Hugo markdown renderer)?

### ISSUE THREAD

**Issue by mr-islam** [vaetas/hugo-footnotes-popup#8]
Hi, thanks for this great utility that I've enjoyed for almost a year!

I just upgraded to a newer version of Hugo and want to use the new Goldmark renderer for some of the new features. The transition was successful, except this library no longer works.

I would guess because the new renderer generates a different kind of HTML output for the footnotes. Goldmark documentation states that it follows [this implementation of footnotes](https://michelf.ca/projects/php-markdown/extra/#footnotes). I haven't found a reference for blackfriday's one to compare though

Someone could always continue using blackfriday for compatibility. But since Goldmark is the new default it's important to support it as well I think

**Comment by inwardmovement** [comment]
I agree.

**Comment by rodrigoalcarazdelaosa** [comment]
Me too. I came here looking for a solution for my footnotes just to see that it doesn't work with the latest versions of Hugo.

Please 🙏🏼

**Comment by vaetas** [comment]
Hey @mr-islam @inwardmovement @rodrigoalcarazdelaosa 

I have been using Goldmark on my website for some time now and this library works like it used to. I checked my `config.toml` file for Hugo and there are some options for Goldmark parsing.

Note the `footnote = true` attribute in extensions part.

```toml
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
```

Am I missing something? I am not following Hugo development a lot so if you talk about different problem please correct me.

Otherwise please try to put config from snippet above into your `config.toml`.

There is also a [docs page for Goldmark configuration](https://gohugo.io/getting-started/configuration-markup#goldmark).
